id: htaccess-config

info:
  name: HTaccess config file
  author: Yash Anand @yashanand155
  severity: informative

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.htaccess"
    matchers:
      - type: word
        words:
          - RewriteRule
          - </IfModule>
          - <IfModule
        condition: and